### ISSUE TITLE
Add docs about changing background?

### ISSUE THREAD

**Issue by xfq** [slidevjs/docs#137]
I've searched for 'background' in https://sli.dev/ with `⌘K` with no results. I think it would be useful if there are some docs on how to change the background color/image.

**Comment by antfu** [comment]
It's just HTML, you can use custom CSS or UnoCSS as you want. We probably won't document every aspect of the Web as Slidev is designed for developers.

**Comment by xfq** [comment]
There seems to be a `background` option in the frontmatter, but it is not clear what the syntax is. Can it be a URL of an image, a color? If it's an image, can it be repeated?
