### ISSUE TITLE
// is shown in docs before code block

### ISSUE THREAD

**Issue by sapphi-red** [slidevjs/docs#151]
![image](https://github.com/slidevjs/docs/assets/49056869/d759ea56-4a75-4772-a9c6-386ad8c35b4b)

But strangely, it doesn't reproduce with `pnpm dev` / `pnpm build && pnpm vitepress serve`.

![image](https://github.com/slidevjs/docs/assets/49056869/9f91ab32-2aec-42ed-be4c-3050d045a631)

Is the deployed docs old?

related: https://github.com/slidevjs/docs/commit/71973c149153b0ecc1f8cc07aea78eb46ba28172

**Comment by antfu** [comment]
Should be fixed by switching to Shiki
