### ISSUE TITLE
[ENHANCEMENT] Add `Addon Gallery` to the documentation

### ISSUE THREAD

**Issue by kravetsone** [slidevjs/docs#170]
It would be convenient to see the list of addons for slidev not only by the slidev/slidev-addon tags in npm

**Comment by antfu** [comment]
Yeah, surely that's a good idea. PR is welcome!

Just note that the documentation source code has now moved to https://github.com/slidevjs/slidev/tree/main/docs, feel free to do it there, and I am closing this here to clean up
