### ISSUE TITLE
[ENHANCEMENT] Missing `magic-move` for Code Block

### ISSUE THREAD

**Issue by jolo-dev** [slidevjs/docs#181]
I saw that at VueJS Amsterdam 2024 by Alex Lichter's [Talk](https://github.com/manniL/talk-hydration-vuejs-amsterdam-2024).

I am surprised that such a cool feature is not in the docs.

**Comment by antfu** [comment]
Yes, we knew. It's tracked in https://github.com/slidevjs/slidev/issues/1335, we will do it later.
