### ISSUE TITLE
Feat: Improve "Built-in Layouts" docs

### ISSUE THREAD

**Issue by luisfelipesdn12** [slidevjs/docs#35]
In my personal use of documentation, one of the most important parts that I miss is the layouts section.
It would be really helpful to quickly see valid layouts and what they do.

---

We could start with simple, maybe have a list with the name and what the layout is, like:

```md
- **center** - Centralize the content blablabla
- **cover** - Displays a background image blablabla
...
```

---

But the perfect way in my opinion would be sub-headings for each layout with example images, etc.

**Comment by antfu** [comment]
Sounds like a plan! PR welcome :)

> But the perfect way in my opinion would be sub-headings for each layout with example images, etc.

I feel this a bit like emoji standard - we could give a direction of built-in theme with some descriptions, but how it will end up like it's up to how themes intemperate them. The images part would be better documented by the themes. (e.g. https://github.com/LinusBorg/slidev-theme-vuetiful#layouts)

**Comment by luisfelipesdn12** [comment]
I agree! The https://github.com/LinusBorg/slidev-theme-vuetiful#layouts is a great reference to the layout docs :).
