### ISSUE TITLE
Feature: Add themes.ts and showcases.ts as shared file between docs repositories

### ISSUE THREAD

**Issue by Dawntraoz** [slidevjs/docs#6]
When adding a theme in the English docs, I noticed that the other languages are not updated, it would be nice to have these files in a generic way to have a single source of truth.

Files:
- [themes.ts](https://github.com/slidevjs/docs/blob/main/.vitepress/themes.ts)
- [showcases.ts](https://github.com/slidevjs/docs/blob/main/.vitepress/showcases.ts)

If you think it's a good idea, I wouldn't mind helping you :)

PS: A great project! I love it too much!

**Comment by antfu** [comment]
Docs will sync up everyday, you will see it tmr, no worries.
