### ISSUE TITLE
Mention PlantUML in Diagrams section

### ISSUE THREAD

**Issue by D3SOX** [slidevjs/docs#76]
I think PlantUML support should be mentioned in the docs [here](https://sli.dev/guide/syntax.html#diagrams)

**Comment by iulover99** [comment]
yeah, the feature are in the demo but there is no mention in the docs make it strange

**Comment by antfu** [comment]
PR welcome!

Just note that the documentation source code has now moved to https://github.com/slidevjs/slidev/tree/main/docs; if this is still relevant, please resend the PR there. Thank you.
